name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: example-application

      - name: Install cucumber dependencies
        run: |
          sudo apt-get install -y \
            libasio-dev \
            libgtest-dev \
            libtclap-dev \
            nlohmann-json3-dev \
            ruby-dev

      - name: Install cucumber
        run: |
          sudo gem install \
            cucumber:9.2.1 \
            cucumber-wire:7.0.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: example-application
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: example-application
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Twister Tests
        working-directory: example-application
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
